#kubectl api-resources | grep -i storage
#kubectl api-versions | grep -i storage
#kubectl explain storageclasses
#kubectl get storageclass
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: awsgp2
provisioner: kubernetes.io/aws-ebs
parameters:
  zone: us-east-1a
  #zones: us-east-1a, us-east-1b
  type: gp2
  fsType: ext4
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: awsio1
provisioner: kubernetes.io/aws-ebs
parameters:
  type: io1 
  zones: us-east-1a
  iopsPerGB: "5"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auto-assign-pv-1
spec:
  storageClassName: awsgp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
