---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auto-assign-pv-1
spec:
  storageClassName: awsgp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auto-assign-pv-2
spec:
  storageClassName: awsio1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auto-assign-pv-3
spec:
  storageClassName: awsgp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
      name: mongodb
  template:
    metadata:
      labels:
        app: mongodb
        name: mongodb
    spec:
      containers:
      - image: mongo
        name: mongodb
        imagePullPolicy: Always
        volumeMounts:
        - name: mongodb-data-1
          mountPath: /data/db
        - name: mongodb-data-2
          mountPath: /data/db2
        - name: mongodb-data-3
          mountPath: /data/db3
      volumes:
      - name: mongodb-data-1
        persistentVolumeClaim: 
          claimName: auto-assign-pv-1
      - name: mongodb-data-2
        persistentVolumeClaim: 
          claimName: auto-assign-pv-2
      - name: mongodb-data-3
        persistentVolumeClaim: 
          claimName: auto-assign-pv-3
      nodeSelector:
          kubernetes.io/hostname: ip-172-20-53-174.ec2.internal
